#!/bin/bash

while true; do

	dwmupdates > /home/user/dwmscripts/dwmupdates.txt

	sleep 3600s

done &

while true; do

	VOL=$(< /home/user/dwmscripts/dwmvol)
	CPU=$(< /home/user/dwmscripts/dwmcpu)
	MEM=$(< /home/user/dwmscripts/dwmmemory)
	NET=$(< /home/user/dwmscripts/dwmnet)
	TEMP=$(< /home/user/dwmscripts/dwmtemp)
	HDD=$(< /home/user/dwmscripts/dwmdisk)
	UPDATES=$(< /home/user/dwmscripts/dwmupdates.txt)
	TIME=$(< /home/user/dwmscripts/dwmclock)
	xsetroot -name "| $CPU | $MEM | $NET | $TEMP | $HDD | $UPDATES | $VOL | $TIME"

	sleep 5s
	
done &
